baseURL = ""
languageCode = "en-us"
theme = "typo"

[params]

# Meta description
description = "A blog about arduino projects"

# Appearance settings
theme = 'auto'
colorPalette = 'eink'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """This is a the website that hosts the blogs for the Arduino projects. This was made with the Hugo
[Typo](https://github.com/tomfran/typo 'Typo GitHub') theme and hosted using GitHub pages. Click on posts to see the different blog articles!
"""

# posts per page
paginationSize = 100

# hides page controls
hidePagination = true

[[params.social]]
name = "github"
url = "https://github.com/reubensand"

# Main menu pages

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'arduino'
noClasses = true
guessSyntax = false
lineNos = true
lineNoStart = 1
lineNumbersInTable = true
tabWidth = 4




# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"